### ISSUE TITLE
Issue deeltaak: benaming 

### ISSUE THREAD

**Issue by miel775** [ambersr/look-and-feel-corporate-identity#20]
Goed dat je de meest recente versie van de stylesheet heb gelinkt aan de html. 

Er zijn echter een paar punten die verbeterd kunnen worden:
- Verander de benaming van de custom properties, (kleur1, kleur2 etc).

@saschavanvliet @reyrey-https

**Comment by ambersr** [comment]
Dit hebben we aangepast! 

Commit: [17312d8245afbf19c6e8329402b35369f03f60a1](https://github.com/kimnikitaschijf/look-and-feel-styleguide/commit/17312d8245afbf19c6e8329402b35369f03f60a1)

```
  /* Kleuren */


  /* beige */
  --primary-background-color: #f9e9c2;
  /* light green */
  --secondary-background-color: #4e7141;
  /* darkgreen */
  --third-background-color: #3c593e;
  /* orange */
  --primary-highlight-color: #ff8d06;
  /* brown */
  --secondary-highlight-color: #491b02;

  /* text-off-white */
  --primary-text-color: #fefefe;
  /* text-darkgreen */
  --secondary-text-color: #2C402D;
  /* red */
  --error-color: #ff0000;
```
