### ISSUE TITLE
hamburger functionaliteit helemaal in de nav?

### ISSUE THREAD

**Issue by KoopReynders** [ambersr/look-and-feel-corporate-identity#22]
https://github.com/ambersr/look-and-feel-corporate-identity/blob/8c8746ed394f366f1d147741cee592bfe4958db6/index.html#L24C1-L38C15

De button voor de hamburger functionaliteit staat nu buiten de `nav`. Het is beter om dit te nesten in de het element zelf. Ook staat de id `#menu` io de lijst, zou je dit niet beter op de nav zelf kunnen zetten? 

Je kan voor deze functionaliteit ook een `<details>` gebruiken. Die kan je tegenwoordig ook animeren met css ... 
Check deze link: https://developer.chrome.com/blog/styling-details

**Comment by ambersr** [comment]
- Ik heb het even opgezocht, het is inderdaad logischer om de button in de ```nav``` te plaatsen. Dit is namelijk belangrijk voor de semantiek van de pagina waardoor gebruikers met een screenreader de pagina makkelijker kunnen lezen. (zie afbeelding).

Commit: https://github.com/ambersr/look-and-feel-corporate-identity/commit/ab5937bbecabe0694b074dac0eb4460d0651b0da

- In de volgende sprint ga ik experimenteren met het ```<details>``` element om als functionaliteit voor de hamburger menu te gebruiken. Ik kom hier later nog op terug!

<img width="625" alt="image" src="https://github.com/user-attachments/assets/527f4b8a-74fd-42f1-b897-92db7b50ab64">


Bron: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

**Comment by KoopReynders** [comment]
Dit doe je heel goed Amber!
